// Comprehensive SabjiRate Database - 150 Items
// Complete with English, Hindi, and Marathi names

export const VEGETABLES = [
  { id: 'v1', en: 'Tomato', hi: 'टमाटर', mr: 'टोमॅटो' },
  { id: 'v2', en: 'Onion', hi: 'प्याज', mr: 'कांदा' },
  { id: 'v3', en: 'Potato', hi: 'आलू', mr: 'बटाटा' },
  { id: 'v4', en: 'Brinjal', hi: 'बैंगन', mr: 'वांगे' },
  { id: 'v5', en: 'Cauliflower', hi: 'फूल गोभी', mr: 'फुलकोबी' },
  { id: 'v6', en: 'Cabbage', hi: 'पत्ता गोभी', mr: 'कोबी' },
  { id: 'v7', en: 'Carrot', hi: 'गाजर', mr: 'गाजर' },
  { id: 'v8', en: 'Capsicum', hi: 'शिमला मिर्च', mr: 'ढोबळी मिरची' },
  { id: 'v9', en: 'Green Chilli', hi: 'हरी मिर्च', mr: 'हिरवी मिरची' },
  { id: 'v10', en: 'Cucumber', hi: 'खीरा', mr: 'काकडी' },
  { id: 'v11', en: 'Lady Finger', hi: 'भिंडी', mr: 'भेंडी' },
  { id: 'v12', en: 'Pumpkin', hi: 'कद्दू', mr: 'भोपळा' },
  { id: 'v13', en: 'Bottle Gourd', hi: 'लौकी', mr: 'दुधी भोपळा' },
  { id: 'v14', en: 'Bitter Gourd', hi: 'करेला', mr: 'कारले' },
  { id: 'v15', en: 'Ridge Gourd', hi: 'तोरई', mr: 'दोडका' },
  { id: 'v16', en: 'Sponge Gourd', hi: 'नेनुआ', mr: 'घोसाळे' },
  { id: 'v17', en: 'Drumstick', hi: 'सहजन', mr: 'शेवग्याची शेंग' },
  { id: 'v18', en: 'Radish', hi: 'मूली', mr: 'मुळा' },
  { id: 'v19', en: 'Beetroot', hi: 'चुकंदर', mr: 'बीट' },
  { id: 'v20', en: 'Sweet Potato', hi: 'शकरकंद', mr: 'रताळे' },
  { id: 'v21', en: 'Garlic', hi: 'लहसुन', mr: 'लसूण' },
  { id: 'v22', en: 'Ginger', hi: 'अदरक', mr: 'आले' },
  { id: 'v23', en: 'Green Peas', hi: 'मटर', mr: 'वाटाणा' },
  { id: 'v24', en: 'French Beans', hi: 'फ्रेंच बीन्स', mr: 'फरसबी' },
  { id: 'v25', en: 'Cluster Beans', hi: 'गवार', mr: 'गवार' },
  { id: 'v26', en: 'Spinach', hi: 'पालक', mr: 'पालक' },
  { id: 'v27', en: 'Fenugreek Leaves', hi: 'मेथी', mr: 'मेथी' },
  { id: 'v28', en: 'Coriander', hi: 'धनिया', mr: 'कोथिंबीर' },
  { id: 'v29', en: 'Spring Onion', hi: 'हरा प्याज', mr: 'पातळ कांदा' },
  { id: 'v30', en: 'Raw Banana', hi: 'कच्चा केला', mr: 'कच्ची केळी' },
  { id: 'v31', en: 'Ivy Gourd', hi: 'कुंदरू', mr: 'तोंडली' },
  { id: 'v32', en: 'Snake Gourd', hi: 'चिचिंडा', mr: 'पडवळ' },
  { id: 'v33', en: 'Ash Gourd', hi: 'पेठा', mr: 'कोहळा' },
  { id: 'v34', en: 'Turnip', hi: 'शलगम', mr: 'नवलकोल' },
  { id: 'v35', en: 'Colocasia', hi: 'अरबी', mr: 'अळू' },
  { id: 'v36', en: 'Green Papaya', hi: 'कच्चा पपीता', mr: 'कच्ची पपई' },
  { id: 'v37', en: 'Broad Beans', hi: 'सेम', mr: 'पावटा' },
  { id: 'v38', en: 'Zucchini', hi: 'तोरी', mr: 'झुकीनी' },
  { id: 'v39', en: 'Mushroom', hi: 'मशरूम', mr: 'अळिंबी' },
  { id: 'v40', en: 'Corn', hi: 'मक्का', mr: 'मका' },
  { id: 'v41', en: 'Green Amaranth', hi: 'चौलाई', mr: 'तांदुळजा' },
  { id: 'v42', en: 'Red Amaranth', hi: 'लाल चौलाई', mr: 'लाल तांदुळजा' },
  { id: 'v43', en: 'Lotus Stem', hi: 'कमल ककड़ी', mr: 'कमळ काडी' },
  { id: 'v44', en: 'Raw Jackfruit', hi: 'कटहल', mr: 'फणस' },
  { id: 'v45', en: 'Kohlrabi', hi: 'गांठ गोभी', mr: 'नवलकोल' },
  { id: 'v46', en: 'Mint Leaves', hi: 'पुदीना', mr: 'पुदिना' },
  { id: 'v47', en: 'Curry Leaves', hi: 'कड़ी पत्ता', mr: 'कढीपत्ता' },
  { id: 'v48', en: 'Green Sorrel', hi: 'अम्बाडी', mr: 'आंबाडी' },
  { id: 'v49', en: 'Elephant Yam', hi: 'सुरन', mr: 'सुरण' },
  { id: 'v50', en: 'Chow Chow', hi: 'चायोटे', mr: 'चौचौ' },
];

export const FRUITS = [
  { id: 'f1', en: 'Apple', hi: 'सेब', mr: 'सफरचंद' },
  { id: 'f2', en: 'Banana', hi: 'केला', mr: 'केळी' },
  { id: 'f3', en: 'Mango', hi: 'आम', mr: 'आंबा' },
  { id: 'f4', en: 'Orange', hi: 'संतरा', mr: 'संत्रा' },
  { id: 'f5', en: 'Sweet Lime', hi: 'मौसंबी', mr: 'मोसंबी' },
  { id: 'f6', en: 'Grapes', hi: 'अंगूर', mr: 'द्राक्ष' },
  { id: 'f7', en: 'Papaya', hi: 'पपीता', mr: 'पपई' },
  { id: 'f8', en: 'Pomegranate', hi: 'अनार', mr: 'डाळिंब' },
  { id: 'f9', en: 'Guava', hi: 'अमरूद', mr: 'पेरू' },
  { id: 'f10', en: 'Watermelon', hi: 'तरबूज', mr: 'कलिंगड' },
  { id: 'f11', en: 'Muskmelon', hi: 'खरबूजा', mr: 'खरबूज' },
  { id: 'f12', en: 'Pineapple', hi: 'अनानास', mr: 'अननस' },
  { id: 'f13', en: 'Strawberry', hi: 'स्ट्रॉबेरी', mr: 'स्ट्रॉबेरी' },
  { id: 'f14', en: 'Chikoo', hi: 'चीकू', mr: 'चिकू' },
  { id: 'f15', en: 'Custard Apple', hi: 'सीताफल', mr: 'सीताफळ' },
  { id: 'f16', en: 'Jamun', hi: 'जामुन', mr: 'जांभूळ' },
  { id: 'f17', en: 'Litchi', hi: 'लीची', mr: 'लिची' },
  { id: 'f18', en: 'Peach', hi: 'आड़ू', mr: 'पीच' },
  { id: 'f19', en: 'Pear', hi: 'नाशपाती', mr: 'नाशपाती' },
  { id: 'f20', en: 'Plum', hi: 'आलूबुखारा', mr: 'आलूबुखारा' },
];

export const DAIRY = [
  { id: 'd1', en: 'Milk', hi: 'दूध', mr: 'दूध' },
  { id: 'd2', en: 'Curd', hi: 'दही', mr: 'दही' },
  { id: 'd3', en: 'Paneer', hi: 'पनीर', mr: 'पनीर' },
  { id: 'd4', en: 'Butter', hi: 'मक्खन', mr: 'लोणी' },
  { id: 'd5', en: 'Ghee', hi: 'घी', mr: 'तूप' },
  { id: 'd6', en: 'Cheese', hi: 'चीज़', mr: 'चीज' },
  { id: 'd7', en: 'Cream', hi: 'मलाई', mr: 'साई' },
  { id: 'd8', en: 'Buttermilk', hi: 'छाछ', mr: 'ताक' },
  { id: 'd9', en: 'Condensed Milk', hi: 'कंडेंस्ड मिल्क', mr: 'कंडेन्स्ड दूध' },
];

export const KIRANA = [
  { id: 'k1', en: 'Rice', hi: 'चावल', mr: 'तांदूळ' },
  { id: 'k2', en: 'Basmati Rice', hi: 'बासमती चावल', mr: 'बासमती तांदूळ' },
  { id: 'k3', en: 'Wheat', hi: 'गेहूं', mr: 'गहू' },
  { id: 'k4', en: 'Atta', hi: 'आटा', mr: 'पीठ' },
  { id: 'k5', en: 'Maida', hi: 'मैदा', mr: 'मैदा' },
  { id: 'k6', en: 'Toor Dal', hi: 'तूर दाल', mr: 'तूर डाळ' },
  { id: 'k7', en: 'Moong Dal', hi: 'मूंग दाल', mr: 'मूग डाळ' },
  { id: 'k8', en: 'Masoor Dal', hi: 'मसूर दाल', mr: 'मसूर डाळ' },
  { id: 'k9', en: 'Chana Dal', hi: 'चना दाल', mr: 'चना डाळ' },
  { id: 'k10', en: 'Urad Dal', hi: 'उड़द दाल', mr: 'उडीद डाळ' },
  { id: 'k11', en: 'Sugar', hi: 'चीनी', mr: 'साखर' },
  { id: 'k12', en: 'Jaggery', hi: 'गुड़', mr: 'गूळ' },
  { id: 'k13', en: 'Salt', hi: 'नमक', mr: 'मीठ' },
  { id: 'k14', en: 'Cooking Oil', hi: 'तेल', mr: 'तेल' },
  { id: 'k15', en: 'Mustard Oil', hi: 'सरसों तेल', mr: 'मोहरी तेल' },
  { id: 'k16', en: 'Groundnut Oil', hi: 'मूंगफली तेल', mr: 'शेंगदाणा तेल' },
  { id: 'k17', en: 'Tea', hi: 'चाय', mr: 'चहा' },
  { id: 'k18', en: 'Coffee', hi: 'कॉफी', mr: 'कॉफी' },
  { id: 'k19', en: 'Poha', hi: 'पोहा', mr: 'पोहे' },
  { id: 'k20', en: 'Rava', hi: 'सूजी', mr: 'रवा' },
  { id: 'k21', en: 'Besan', hi: 'बेसन', mr: 'बेसन' },
  { id: 'k22', en: 'Sooji', hi: 'सूजी', mr: 'रवा' },
  { id: 'k23', en: 'Spices Mix', hi: 'मसाले', mr: 'मसाले' },
  { id: 'k24', en: 'Red Chilli Powder', hi: 'लाल मिर्च', mr: 'लाल तिखट' },
  { id: 'k25', en: 'Turmeric', hi: 'हल्दी', mr: 'हळद' },
  { id: 'k26', en: 'Cumin Seeds', hi: 'जीरा', mr: 'जिरे' },
  { id: 'k27', en: 'Mustard Seeds', hi: 'राई', mr: 'मोहरी' },
  { id: 'k28', en: 'Tamarind', hi: 'इमली', mr: 'चिंच' },
  { id: 'k29', en: 'Dry Coconut', hi: 'सूखा नारियल', mr: 'सुकं खोबरं' },
  { id: 'k30', en: 'Dates', hi: 'खजूर', mr: 'खजूर' },
  { id: 'k31', en: 'Cashew', hi: 'काजू', mr: 'काजू' },
  { id: 'k32', en: 'Raisins', hi: 'किशमिश', mr: 'मनुका' },
  { id: 'k33', en: 'Red Chilli', hi: 'लाल मिर्च', mr: 'लाल मिरची' },
  { id: 'k34', en: 'Coriander Powder', hi: 'धनिया पाउडर', mr: 'कोथिंबीर पावडर' },
  { id: 'k35', en: 'Red Chilli Flakes', hi: 'लाल मिर्च के टुकड़े', mr: 'लाल मिरचीचे तुकडे' },
  { id: 'k36', en: 'Fenugreek Seeds', hi: 'मेथी के बीज', mr: 'मेथीची दाणी' },
  { id: 'k37', en: 'Black Pepper', hi: 'काली मिर्च', mr: 'काळी मिरी' },
  { id: 'k38', en: 'Clove', hi: 'लौंग', mr: 'लवंग' },
  { id: 'k39', en: 'Cinnamon', hi: 'दालचीनी', mr: 'दालचिनी' },
  { id: 'k40', en: 'Cardamom', hi: 'इलायची', mr: 'वेलची' },
];

// Export all items combined for easy access
export const ALL_ITEMS = {
  VEGETABLES,
  FRUITS,
  DAIRY,
  KIRANA,
};

// Category enum
export enum Category {
  VEGETABLES = 'VEGETABLES',
  FRUITS = 'FRUITS',
  DAIRY = 'DAIRY',
  KIRANA = 'KIRANA',
}

// Unit types per category (STRICT RULES)
export const CATEGORY_UNITS = {
  [Category.VEGETABLES]: { type: 'GRAMS', baseUnit: 'KILOGRAM' },
  [Category.FRUITS]: { type: 'GRAMS', baseUnit: 'KILOGRAM' },
  [Category.DAIRY]: { type: 'MILLILITERS', baseUnit: 'LITER' },
  [Category.KIRANA]: { type: 'GRAMS', baseUnit: 'KILOGRAM' },
};

// Canonical weight mappings (LOCKED - NO ALTERNATIVES)
export const CANONICAL_WEIGHTS = {
  // Vegetable/Fruit/Kirana weights (grams)
  VEG_WEIGHTS: [
    { grams: 62.5, localTerm: 'Half Chatak', hi: 'आधा छटक', mr: 'अर्धा छटक' },
    { grams: 125, localTerm: '1 Chatak', hi: '1 छटक', mr: '1 छटक' },
    { grams: 250, localTerm: 'Pav', hi: 'पाव', mr: 'पाव' },
    { grams: 375, localTerm: 'Dedh Pav', hi: 'डेढ़ पाव', mr: 'डेढ पाव' },
    { grams: 500, localTerm: 'Half Kilo', hi: 'आधा किलो', mr: 'अर्धा किलो' },
    { grams: 750, localTerm: 'Paune Kilo', hi: 'पौने किलो', mr: 'पौने किलो' },
    { grams: 1000, localTerm: '1 Kilo', hi: '1 किलो', mr: '1 किलो' },
  ],
  // Dairy weights (milliliters) - ABSOLUTE RULE: NO GRAMS/CHATAK/PAV
  DAIRY_WEIGHTS: [
    { ml: 250, localTerm: 'Quarter (पाव)', hi: 'पाव', mr: 'पाव' },
    { ml: 500, localTerm: 'Half Liter', hi: 'अर्धा लीटर', mr: 'अर्धा लीटर' },
    { ml: 750, localTerm: 'Paune Liter', hi: 'पौने लीटर', mr: 'पौने लीटर' },
    { ml: 1000, localTerm: '1 Liter', hi: '1 लीटर', mr: '1 लीटर' },
  ],
};
